version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 80:8000
    # volumes:
    #   - ./:/usr/src/app:ro
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./.env #pointing to env file
  postgres:
    image: postgres
    # env_file:
    #   - ./.env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_URL} # to reference env variable
      - POSTGRES_DB=fastap-social
    
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db:
