name: Build and Deploy Code

# on:
#   push:
#     branches:
#       - "deploy"
#       - "other_branch"
#   pull_request:
#     branches:
#       - "deploy"
#       - "test"
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: install python version 3.10
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest -v
